### ISSUE TITLE
"--print-monitor-info" error

### ISSUE THREAD

**Issue by Anerag** [xhsdf/pxdo#2]
`$ pxdo.py --print-monitor-info` prints `('Unexpected error:', <class 'struct.error'>)` and hangs. Python-xlib installed, everything up to date. Running on Ubuntu Artful (dev branch).

Any help?

**Comment by xhsdf** [comment]
Can you comment out the try-except (lines 22, 38 and 39) and post the output again?

**Comment by Anerag** [comment]
Here you go:
```
Traceback (most recent call last):
  File "./pxdo.py", line 215, in <module>
    main(argv[1:])
  File "./pxdo.py", line 32, in main
    print_monitor_info()
  File "./pxdo.py", line 54, in print_monitor_info
    for monitor in Monitor.get_monitors():
  File "./pxdo.py", line 80, in get_monitors
    crtc_info = display.xrandr_get_crtc_info(crtc, resources.config_timestamp)
  File "/usr/lib/python2.7/dist-packages/Xlib/ext/randr.py", line 734, in get_crtc_info
    config_timestamp=config_timestamp,
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1478, in __init__
    self.reply()
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1490, in reply
    self._display.send_and_recv(request = self._serial)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 556, in send_and_recv
    gotreq = self.parse_response(request)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 643, in parse_response
    gotreq = self.parse_request_response(request) or gotreq
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 729, in parse_request_response
    req._parse_response(self.data_recv[:self.request_length])
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1502, in _parse_response
    self._data, d = self._reply.parse_binary(data, self._display, rawdict = 1)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1325, in parse_binary
    return self.parse_binary(data, display, rawdict)
  File "<string>", line 14, in parse_binary
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 510, in parse_binary_value
    v = struct.unpack(scode, data[pos: pos + slen])
struct.error: unpack requires a string argument of length 4
```

**Comment by xhsdf** [comment]
Looks like this: https://github.com/python-xlib/python-xlib/issues/58

**Comment by Anerag** [comment]
Well then, solved by installing python-xlib from git instead of Ubuntu repos, which were horribly out of date (ver. 0.14!). I guess it's expected to have packages lag behind a bit but this is just ridiculous. Maybe discourage using distro repos in the readme.

Thanks for the help! Closing...

**Comment by xhsdf** [comment]
>Maybe discourage using distro repos in the readme.

I've added a warning.
